name: AWS ELB Deploy
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Generate deployment package
      run: zip -r complex.zip . -x '*.git*'

    - name: Get timestamp
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Run string replace
      uses: frabert/replace-string-action@master
      id: format-time
      with:
        pattern: '[:\.]+'
        string: "${{ steps.current-time.outputs.time }}"
        replace-with: '-'
        flags: 'g'

    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: complex
        environment_name: Complex-env
        version_label: "complex-${{ steps.format-time.outputs.replaced }}"
        region: us-east-1
        deployment_package: complex.zip

    - name: Deployed
      run: echo "App Deployed to ELB"
